entity: jandylin
project: faster-sgd-gp
program: scripts/obtain_samples.py

method: grid
parameters:
  dataset_config.split:
    values: [0, 1, 2, 3, 4]
  model_name:
    values: ["cg"]
  cg_sampling_config.batch_size:
    values: [512]
  cg_sampling_config.maxiter:
    values: [1000]

command:
  - python
  - ${program}
  - 17bb59c7a4e186597fe98347175642c99c8403e2
  - --config
  - configs/default.py:pol
  - --config.wandb.log
  - --config.wandb.log_artifact
  - --noconfig.compute_exact_soln
