entity: shreyaspadhy
project: scalable-gps
program: scripts/regression_sweep.py

method: grid
parameters:
  train_config.batch_size:
    values: [64, 128, 256, 512, 1024]
  train_config.learning_rate:
    values: [0.01, 0.1, 0.2, 0.5]
  train_config.iterations:
    values: [200000]

command:
  - python
  - ${program}
  - --config
  - configs/default.py:kin40k
  - --config.wandb.log
  - --noconfig.compute_exact_soln
