entity: shreyaspadhy
project: scalable-gps
program: scripts/obtain_samples.py

method: grid
parameters:
  dataset_config.split:
    values: [0, 1, 2, 4]
  model_name:
    values: ["vi"]
  vi_config.num_inducing_points:
    values: [4096]

command:
  - python
  - ${program}
  - 17bb59c7a4e186597fe98347175642c99c8403e2
  - --config
  - configs/default.py:3droad
  - --config.wandb.log
  - --noconfig.compute_exact_soln
