entity: jandylin
project: faster-sgd-gp
program: scripts/thompson_sampling.py

method: grid
parameters:
  thompson.model_name:
    values: ["SGDGP"]
  thompson.seed:
    values: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
  thompson.D:
    values: [8]
  thompson.length_scale:
    values: [0.1, 0.2, 0.3, 0.4, 0.5]
  train_config.grad_variant:
    values: ['vanilla']
  sampling_config.grad_variant:
    values: ['vanilla']
  train_config.iterations:
    values: [15000]
  sampling_config.iterations:
    values: [15000]
  train_config.learning_rate:
    values: [3e-1]
  sampling_config.learning_rate:
    values: [3e-4]

command:
  - python
  - ${program}
  - 17bb59c7a4e186597fe98347175642c99c8403e2
  - --config
  - configs/thompson_config.py
  - --config.wandb.log
  - --noconfig.compute_exact_soln
